version: "3.7"

services:
  nginx:
    dns:
      - 8.8.8.8
      - 4.4.4.4
    build:
      context: ./images
      dockerfile: nginx.Dockerfile
    working_dir: /var/www/html
    container_name: web
    ports:
      - "80:80"
    volumes:
      - ./projects:/var/www/html
      - ./logs/nginx_log:/var/log/nginx
      - ./config/nginx/project1.conf:/etc/nginx/conf.d/project1.conf
      - ./config/nginx/project2.conf:/etc/nginx/conf.d/project2.conf
    links:
      - php
      - mysql
      - mongodb

  php:
    build:
      context: ./images
      dockerfile: php.Dockerfile
    container_name: api
    volumes:
      - ./projects:/var/www/html
      - ./logs/php-fpm/php-fpm.log:/var/log/php-fpm.log

  mysql:
    build:
      context: ./images
      dockerfile: mysql.Dockerfile
    container_name: mysql
    ports:
      - "13306:13306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    volumes:
      - ./data/mongodb/data/db:/data/db
      - ./data/mongodb/data/configdb:/data/configdb
    ports:
      - "27017:27017"
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
  mongo-express:
    image: mongo-express
    container_name: mexpress
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_URL=mongodb://root:root@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    links:
      - mongodb
    restart: unless-stopped
    ports:
      - "8081:8081"
